import {defaults} from '../contract';
import {validateImageSize} from './limits';
import {palette} from '../color';
import type {BrowserPattern,Request,Event} from './protocol';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let worker:Worker|null=null,jobId='',source:File|null=null,busy=false,selected:BrowserPattern|null=null,page=0,dirty=false,lastError='';
const items:BrowserPattern[]=[],urls=new Set<string>();let downloadUrl:string|null=null;
function status(text:string){$('status').textContent=text;}
function error(e:unknown){lastError=e instanceof Error?e.message:String(e);$('error').textContent=lastError;status('Operation failed.');}
function clearExport(){if(downloadUrl){URL.revokeObjectURL(downloadUrl);urls.delete(downloadUrl);downloadUrl=null;}$('download').hidden=true;}
function setBusy(value:boolean){busy=value;for(const id of ['single','batch'])$<HTMLButtonElement>(id).disabled=value||!source;$<HTMLButtonElement>('cancel').disabled=!value;for(const id of ['export-labeled','export-unlabeled'])$<HTMLButtonElement>(id).disabled=value||!selected;}
function terminate(){worker?.terminate();worker=null;setBusy(false);}
function createWorker(){terminate();worker=new Worker(new URL('./worker.js',location.href),{type:'module'});worker.onerror=e=>{error(e.message);terminate();};worker.onmessage=({data}:{data:Event})=>{if(data.jobId!==jobId)return;if(data.type==='style'){items.push(data.item);dirty=true;status(`Generated ${data.completed}/${data.total}`);$<HTMLProgressElement>('progress').max=data.total;$<HTMLProgressElement>('progress').value=data.completed;}else if(data.type==='complete'){status(`Finished: ${items.length} styles`);terminate();if(!selected&&items[0])select(items[0]);}else if(data.type==='error'){error(data.message);terminate();}else if(data.type==='export'){if(downloadUrl){URL.revokeObjectURL(downloadUrl);urls.delete(downloadUrl);}downloadUrl=URL.createObjectURL(data.blob);urls.add(downloadUrl);const a=$<HTMLAnchorElement>('download');a.href=downloadUrl;a.download=data.filename;a.textContent=`Download ${data.filename.includes('unlabeled')?'unlabeled':'labeled'} PNG`;a.hidden=false;status(`PNG ready: ${(data.blob.size/1024).toFixed(0)} KiB. Use the download link.`);terminate();}};return worker;}
function draw(pattern:BrowserPattern,canvas:HTMLCanvasElement,cell:number){canvas.width=pattern.width*cell;canvas.height=pattern.height*cell;const ctx=canvas.getContext('2d',{alpha:false})!;for(let y=0;y<pattern.height;y++)for(let x=0;x<pattern.width;x++){ctx.fillStyle=palette[pattern.indices[y*pattern.width+x]].hex;ctx.fillRect(x*cell,y*cell,cell,cell);}}
function select(item:BrowserPattern){if(selected!==item)clearExport();selected=item;draw(item,$<HTMLCanvasElement>('large'),Number($<HTMLSelectElement>('preview-size').value));$('detail').hidden=false;for(const button of document.querySelectorAll<HTMLButtonElement>('#gallery button'))button.classList.toggle('selected',button.dataset.id===item.id);setBusy(busy);}
function gallery(){dirty=false;const pages=Math.max(1,Math.ceil(items.length/12));page=Math.min(page,pages-1);$('gallery').replaceChildren();for(const item of items.slice(page*12,(page+1)*12)){const button=document.createElement('button');button.dataset.id=item.id;button.setAttribute('aria-label',`View style ${item.id}`);button.classList.toggle('selected',item===selected);const canvas=document.createElement('canvas');draw(item,canvas,4);button.append(canvas);button.onclick=()=>select(item);$('gallery').append(button);}$('page').textContent=`Page ${page+1}/${pages} · ${items.length} styles`;$<HTMLButtonElement>('previous').disabled=page===0;$<HTMLButtonElement>('next').disabled=page===pages-1;}
setInterval(()=>{if(dirty)gallery();},1000);
function accept(file:File){if(busy)return;clearExport();source=file;items.length=0;selected=null;page=0;dirty=true;$('detail').hidden=true;$('filename').textContent=file.name;status('Image selected. All processing stays in this browser.');setBusy(false);}
$('choose').onclick=()=>$<HTMLInputElement>('file').click();
$<HTMLInputElement>('file').onchange=e=>{const f=(e.target as HTMLInputElement).files?.[0];if(f)accept(f);};
document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>{e.preventDefault();const file=e.dataTransfer?.files[0];if(file)accept(file);});
async function decode(file:File){const image=await createImageBitmap(file,{imageOrientation:'none',premultiplyAlpha:'none',colorSpaceConversion:'none'});try{validateImageSize(image.width,image.height);const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(image,0,0);const rgba=ctx.getImageData(0,0,image.width,image.height).data,rgb=new Uint8Array(image.width*image.height*3);for(let i=0,j=0;i<rgba.length;i+=4,j+=3){rgb[j]=rgba[i];rgb[j+1]=rgba[i+1];rgb[j+2]=rgba[i+2];}canvas.width=1;canvas.height=1;return {pixels:rgb,width:image.width,height:image.height};}finally{image.close();}}
async function generate(batch:boolean){if(!source||busy)return;try{$('error').textContent='';lastError='';const w=createWorker();setBusy(true);jobId=crypto.randomUUID();status('Decoding image…');const decoded=await decode(source);if(w!==worker)return;items.length=0;selected=null;page=0;dirty=true;const settings={...defaults,jobId,cellSize:40};const message:Request={type:'generate',jobId,...decoded,batch,settings};w.postMessage(message,[decoded.pixels.buffer]);status('Generating in worker…');}catch(e){error(e);terminate();}}
$('single').onclick=()=>void generate(false);$('batch').onclick=()=>void generate(true);$('cancel').onclick=()=>{jobId='cancelled';terminate();status('Cancelled. Completed patterns remain available.');};
$('previous').onclick=()=>{page--;gallery();};$('next').onclick=()=>{page++;gallery();};
$('preview-size').onchange=()=>{if(selected)select(selected);};
function exportPattern(labels:boolean){if(!selected||busy)return;try{const w=createWorker();setBusy(true);jobId=crypto.randomUUID();const message:Request={type:'export',jobId,pattern:selected,cellSize:Number($<HTMLSelectElement>('final-size').value),labels};w.postMessage(message);status('Rendering PNG in worker…');}catch(e){error(e);terminate();}}
$('export-labeled').onclick=()=>exportPattern(true);$('export-unlabeled').onclick=()=>exportPattern(false);
window.addEventListener('pagehide',()=>{terminate();for(const url of urls)URL.revokeObjectURL(url);urls.clear();});
// Read-only test snapshot for this prototype. Removed when migrating the full UI.
Object.defineProperty(window,'prototypeResults',{get:()=>({error:lastError,items:items.map(p=>({id:p.id,width:p.width,height:p.height,grid:Array.from({length:p.height},(_,y)=>Array.from(p.indices.subarray(y*p.width,(y+1)*p.width),i=>palette[i].code))}))})});
if(!('Worker'in window)||!('createImageBitmap'in window)||!('OffscreenCanvas'in window)){error('This prototype needs a modern browser with Worker, createImageBitmap and OffscreenCanvas support.');}else setBusy(false);
gallery();
