const {app,BrowserWindow,dialog}=require('electron');
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
process.env.BEAD_TEST_OUTPUT=path.resolve('generated/integration');
process.env.BEAD_TEST_OFFSCREEN='1';
app.disableHardwareAcceleration();
dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path.resolve('fixtures/regression/gradient.png')]});
require('../dist/main.js');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(fn,message,timeout=90000){const start=Date.now();while(Date.now()-start<timeout){if(await fn())return;await delay(100);}throw Error('Timed out: '+message);}
app.whenReady().then(async()=>{try{
  await wait(()=>BrowserWindow.getAllWindows().length,'window');const win=BrowserWindow.getAllWindows()[0];
  win.hide();const run=code=>win.webContents.executeJavaScript(code);
  await wait(async()=>!win.webContents.isLoading()&&await run('!!window.beads'),'preload');
  assert.equal(await run('typeof require'),'undefined');
  assert.equal(await run('window.beads.openPath("C:/Windows").then(()=>false,()=>true)'),true);
  await run('document.getElementById("choose").click()');
  await wait(()=>run('document.getElementById("source-name").textContent === "gradient.png"'),'source loaded');
  await run('document.getElementById("maxWidth").value=16;document.getElementById("maxHeight").value=16;document.getElementById("cellSize").value=20;document.getElementById("generate").click()');
  await wait(()=>run('document.getElementById("status").textContent === "Pattern generated."'),'single generation');
  await wait(()=>run('document.getElementById("single-preview").naturalWidth>0'),'single preview');
  await fs.mkdir('generated/smoke',{recursive:true});await fs.writeFile('generated/smoke/artistic.png',(await win.webContents.capturePage()).toPNG());
  await run('document.getElementById("batch-tab").click();document.getElementById("generate-batch").click()');
  await wait(()=>run('document.getElementById("status").textContent === "Finished: 96 styles."'),'batch');
  await wait(()=>run('document.querySelectorAll("#gallery button").length>0'),'gallery');
  await run('document.querySelector("#gallery button").click()');
  await wait(()=>run('document.getElementById("detail").open && document.getElementById("detail-image").naturalWidth>0'),'enlarged preview');
  await run('document.getElementById("close-detail").click();document.getElementById("next").click()');
  assert.match(await run('document.getElementById("page-info").textContent'),/^Page 2/);
  assert.equal(await run('document.querySelectorAll("#gallery [title]").length'),0);
  await run('document.getElementById("final-cell").value=40;document.getElementById("finals").click()');
  await wait(()=>run('document.getElementById("status").textContent === "Both final PNGs are ready."'),'finals');
  assert.equal(await run('document.getElementById("batch-panel").hidden'),false);
  assert.equal(await run('document.querySelectorAll("#final-output button").length'),2);
  await run('document.getElementById("gallery").scrollIntoView({block:"start"})');await delay(150);
  await fs.writeFile('generated/smoke/batch.png',(await win.webContents.capturePage()).toPNG());
  await run('document.getElementById("generate-batch").click()');await delay(250);
  await run('document.getElementById("cancel").click()');
  await wait(()=>run('document.getElementById("status").textContent.startsWith("Cancelled.")'),'cancellation');
  assert.equal(await run('document.getElementById("generate-batch").disabled'),false);
  console.log('Electron smoke passed: isolation, file access, file picker, single, 96-style batch, gallery, pagination, preview, final pair, cancellation.');app.exit(0);
}catch(e){console.error(e);const win=BrowserWindow.getAllWindows()[0];if(win)console.error(await win.webContents.executeJavaScript('document.getElementById("status").textContent+" / "+document.getElementById("error-text").textContent'));app.exit(1);}});
