import {spawn,type ChildProcess} from 'node:child_process';
import path from 'node:path';
import {planBatch,validateSettings,type PatternGenerator,type GenerationSettings,type GenerationResult,type BatchSettings,type BatchResult,type ProgressHandler} from './contract';
export class PythonPatternGenerator implements PatternGenerator {
  private children=new Map<string,ChildProcess>();private cancelled=new Set<string>();
  constructor(private root:string,private python='python'){}
  async cancel(id:string){this.cancelled.add(id);this.children.get(id)?.kill();}
  generateSingle(settings:GenerationSettings,onProgress?:ProgressHandler):Promise<GenerationResult>{const s=validateSettings(settings);return new Promise((resolve,reject)=>{const child=spawn(this.python,[path.join(this.root,'scripts/python_bridge.py')],{stdio:['pipe','pipe','pipe'],windowsHide:true,shell:false});this.children.set(s.jobId,child);let out='',err='';child.stdout.on('data',data=>{out+=data;let index;while((index=out.indexOf('\n'))>=0){const line=out.slice(0,index);out=out.slice(index+1);try{const value=JSON.parse(line);if(value.type==='result')resolve(value.result);else if(value.type==='error')reject(Object.assign(Error(value.error.message),value.error));else if(value.type==='progress')onProgress?.(value);}catch(e){reject(e);}}});child.stderr.on('data',data=>err+=data);child.on('error',reject);child.on('close',code=>{this.children.delete(s.jobId);if(code!==0)reject(Error(this.cancelled.has(s.jobId)?'Cancelled':err||`Python exited ${code}`));});child.stdin.end(JSON.stringify(s)+'\n');});}
  async generateBatch(s:BatchSettings,onProgress?:ProgressHandler):Promise<BatchResult>{const plan=planBatch(s),items:BatchResult['items']=[];this.cancelled.delete(s.base.jobId);for(const settings of plan){if(this.cancelled.has(s.base.jobId))break;try{const r=await this.generateSingle(settings);items.push({pngPath:r.pngPath,width:r.width,height:r.height,settings:r.settings});onProgress?.({jobId:s.base.jobId,completed:items.length,total:plan.length,message:`Generated ${items.length}/${plan.length}`,item:items.at(-1)});}catch(e){if(this.cancelled.has(s.base.jobId))break;throw e;}}return {jobId:s.base.jobId,items,cancelled:this.cancelled.has(s.base.jobId)};}
}
