import {defaults,numericKeys,samplings,filters,distances,dithers,preset,presetValues,planBatch,parseStyle,styleLabel,bounds,type GenerationSettings,type Ranges,type GalleryItem,type GenerationResult} from './contract';
import type {JobKind} from './api';
import './api';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const api=window.beads;let inputPath='',jobId='',activeKind:JobKind='single',outputDir='',galleryDir='',busy=false,page=0,perPage=12,selected:GalleryItem|undefined,items:GalleryItem[]=[],dirty=false;
const imageCache=new Map<string,Promise<string>>();
const names:Record<string,string>={maxWidth:'Maximum width (beads)',maxHeight:'Maximum height (beads)',cellSize:'PNG pixels per bead',gridDisplay:'Grid display',sampling:'Sampling',resize_filter:'Resize filter',distance:'Color distance',dither:'Dithering',pre_blur:'Pre-blur',sharpen:'Sharpen',gamma:'Gamma',contrast:'Contrast',saturation:'Saturation',dither_strength:'Dither strength (%)'};
function field(group:string,key:string,value:string|number,options?:readonly string[],min?:number,max?:number,step=1){const label=document.createElement('label');label.textContent=names[key];const input=options?document.createElement('select'):document.createElement('input');input.id=key;if(input instanceof HTMLSelectElement)for(const v of options!){const option=document.createElement('option');option.value=v;option.textContent=v;input.append(option);}else{input.type='number';input.min=String(min??0);input.max=String(max??200);input.step=String(step);}input.value=String(value);label.append(input);$(group).append(label);}
field('grid-fields','maxWidth',104,undefined,1,200);field('grid-fields','maxHeight',104,undefined,1,200);field('grid-fields','cellSize',100,undefined,1,160);field('grid-fields','gridDisplay','none',['none','subtle','white','adaptive']);
field('style-fields','sampling','average',samplings);field('style-fields','resize_filter','box',filters);field('style-fields','distance','lab',distances);field('style-fields','dither','none',dithers);
for(const key of numericKeys)field('adjust-fields',key,defaults[key],undefined,...bounds[key],key==='dither_strength'?1:.05);
for(const series of 'ABCDEFGHM'){const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.checked=true;input.value=series;label.append(input,series);$('series').append(label);}
for(const name of Object.keys(presetValues)){const option=document.createElement('option');option.value=name;option.textContent=name;$('preset').append(option);}
function loadRanges(ranges:Ranges){$('ranges').replaceChildren();for(const key of numericKeys){const row=document.createElement('tr');const name=document.createElement('td');name.textContent=names[key];row.append(name);for(const which of ['min','max','step'] as const){const td=document.createElement('td'),input=document.createElement('input');input.id=`range-${key}-${which}`;input.type='number';input.step='any';input.value=String(ranges[key][which]);input.setAttribute('aria-label',`${names[key]} ${which}`);td.append(input);row.append(td);}$('ranges').append(row);}}
loadRanges(preset('Quick Baseline'));
function ranges():Ranges{return Object.fromEntries(numericKeys.map(key=>[key,Object.fromEntries(['min','max','step'].map(which=>[which,Number($<HTMLInputElement>(`range-${key}-${which}`).value)]))])) as Ranges;}
function settings():GenerationSettings{const s={...defaults,inputPath,outputDir,jobId:jobId||'estimate'};for(const key of Object.keys(names)) (s as unknown as Record<string,unknown>)[key]=typeof (defaults as unknown as Record<string,unknown>)[key]==='number'?Number($<HTMLInputElement>(key).value):$<HTMLInputElement>(key).value;s.series=Array.from(document.querySelectorAll<HTMLInputElement>('#series input:checked')).map(i=>i.value).join('');return s;}
function status(text:string){$('status').textContent=text;}
function showError(error:unknown){$('error-text').textContent=error instanceof Error?error.message:String(error);if(!$<HTMLDialogElement>('error').open)$<HTMLDialogElement>('error').showModal();}
function action(id:string,fn:()=>unknown){$(id).addEventListener('click',()=>{Promise.resolve().then(fn).catch(showError);});}
function setBusy(value:boolean){busy=value;for(const button of document.querySelectorAll<HTMLButtonElement>('.run'))button.disabled=value||!inputPath;$<HTMLButtonElement>('cancel').disabled=!value;$<HTMLButtonElement>('choose').disabled=value;$<HTMLButtonElement>('finals').disabled=value||!selected;}
function tab(batch:boolean){$('art-panel').hidden=batch;$('batch-panel').hidden=!batch;$('art-tab').classList.toggle('active',!batch);$('batch-tab').classList.toggle('active',batch);$('art-tab').setAttribute('aria-selected',String(!batch));$('batch-tab').setAttribute('aria-selected',String(batch));}
function accept(image:{path:string;name:string;preview:string}|null){if(!image)return;inputPath=image.path;$('source-name').textContent=image.name;$<HTMLImageElement>('source-preview').src=image.preview;$('source-preview').hidden=false;items=[];selected=undefined;page=0;galleryDir='';dirty=true;$<HTMLButtonElement>('gallery-folder').disabled=true;$('final-output').replaceChildren();setBusy(false);status('Image loaded. Adjust settings or explore all styles.');}
action('choose',async()=>accept(await api.chooseImage()));action('art-tab',()=>tab(false));action('batch-tab',()=>tab(true));
document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>e.preventDefault());$('drop').addEventListener('dragover',e=>{e.preventDefault();$('drop').classList.add('drag');});$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('drag'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('drag');if(busy)return;const file=(e as DragEvent).dataTransfer?.files[0];if(file)api.dropImage(file).then(accept).catch(showError);});
async function start(kind:JobKind,s:GenerationSettings){jobId=crypto.randomUUID();s.jobId=jobId;activeKind=kind;setBusy(true);status('Starting generation…');$<HTMLProgressElement>('progress').value=0;try{const r=await api.start({kind,settings:kind==='batch'?{base:s,ranges:ranges()}:s});outputDir=r.outputDir;$<HTMLButtonElement>('output-folder').disabled=false;if(kind==='batch'){galleryDir=outputDir;$<HTMLButtonElement>('gallery-folder').disabled=false;}}catch(e){setBusy(false);throw e;}}
action('generate',()=>start('single',settings()));
function batchSettings(){return {...settings(),cellSize:Number($<HTMLInputElement>('batch-cell').value),gridDisplay:'none' as const,labels:false};}
function estimate(){const s=batchSettings();if(s.cellSize<10||s.cellSize>40)throw Error('Batch cells must be between 10 and 40 pixels');const count=planBatch({base:s,ranges:ranges()}).length;const seconds=count*(.35+s.maxWidth*s.maxHeight*s.cellSize*s.cellSize/25000000);$('estimate-text').textContent=`${count.toLocaleString()} styles · roughly ${Math.max(1,Math.round(seconds/60))} minutes (hardware-dependent)`;return count;}
action('estimate',estimate);action('generate-batch',()=>{estimate();items=[];selected=undefined;page=0;dirty=true;return start('batch',batchSettings());});
action('load-preset',()=>{loadRanges(preset($<HTMLSelectElement>('preset').value));$<HTMLInputElement>('batch-cell').value='20';estimate();});
function applyStyle(s:Partial<GenerationSettings>){for(const [key,value] of Object.entries(s)){const el=document.getElementById(key) as HTMLInputElement|null;if(el)el.value=String(value);}status('Imported style settings.');}
action('import',()=>applyStyle(parseStyle($<HTMLInputElement>('style-import').value)));action('import-selected',()=>{if(selected){applyStyle(selected.settings);tab(false);}});
action('cancel',async()=>{status('Cancelling…');await api.cancel(jobId);});action('output-folder',()=>api.openPath(outputDir));action('gallery-folder',()=>api.openPath(galleryDir));action('open-selected',()=>selected&&api.openPath(selected.pngPath));
action('finals',()=>{if(!selected)return;const s={...selected.settings,jobId:'finals',cellSize:Number($<HTMLInputElement>('final-cell').value),label:styleLabel(selected.settings),gridDisplay:$<HTMLSelectElement>('gridDisplay').value as GenerationSettings['gridDisplay']};return start('finals',s);});
action('close-detail',()=>$<HTMLDialogElement>('detail').close());action('close-error',()=>$<HTMLDialogElement>('error').close());
function cached(file:string){let p=imageCache.get(file);if(!p){p=api.preview(file);imageCache.set(file,p);p.catch(()=>imageCache.delete(file));}return p;}
async function select(item:GalleryItem){selected=item;for(const button of document.querySelectorAll<HTMLButtonElement>('#gallery button')){const yes=button.dataset.path===item.pngPath;button.classList.toggle('selected',yes);button.setAttribute('aria-pressed',String(yes));}for(const id of ['import-selected','open-selected'])$<HTMLButtonElement>(id).disabled=false;$<HTMLButtonElement>('finals').disabled=busy;const url=await cached(item.pngPath);if(selected!==item)return;$<HTMLImageElement>('detail-image').src=url;if(!$<HTMLDialogElement>('detail').open)$<HTMLDialogElement>('detail').showModal();}
function refreshGallery(){dirty=false;const pages=Math.max(1,Math.ceil(items.length/perPage));page=Math.min(page,pages-1);$('gallery').replaceChildren();$('gallery-empty').hidden=items.length>0;for(const [index,item] of items.slice(page*perPage,(page+1)*perPage).entries()){const button=document.createElement('button');button.dataset.path=item.pngPath;button.classList.toggle('selected',selected===item);button.setAttribute('aria-label',`Preview style ${page*perPage+index+1}`);button.setAttribute('aria-pressed',String(selected===item));const img=document.createElement('img');img.alt='Bead pattern preview';button.append(img);button.addEventListener('click',()=>select(item).catch(showError));$('gallery').append(button);cached(item.pngPath).then(url=>img.src=url).catch(showError);}$('page-info').textContent=`Page ${page+1} of ${pages} · ${items.length} styles`;$<HTMLButtonElement>('previous').disabled=page===0;$<HTMLButtonElement>('next').disabled=page===pages-1;for(const id of ['import-selected','open-selected','finals'])$<HTMLButtonElement>(id).disabled=!selected||(id==='finals'&&busy);}
action('previous',()=>{page=Math.max(0,page-1);refreshGallery();});action('next',()=>{page++;refreshGallery();});
new ResizeObserver(()=>{const width=$('gallery').clientWidth;if(!width)return;const count=Math.max(1,Math.floor((width+14)/164))*3;if(count!==perPage){perPage=count;dirty=true;}}).observe($('gallery'));
setInterval(()=>{if(dirty)refreshGallery();},1000);
api.onEvent(event=>{if(event.type==='progress'&&event.event){const p=event.event;if(p.jobId!==jobId)return;status(p.message);$<HTMLProgressElement>('progress').max=p.total;$<HTMLProgressElement>('progress').value=p.completed;if(activeKind==='batch'&&p.item){items.push(p.item);dirty=true;}}
  if(event.type==='result'){setBusy(false);status(activeKind==='batch'?`Finished: ${items.length} styles.`:activeKind==='finals'?'Both final PNGs are ready.':'Pattern generated.');if(activeKind==='single'){const r=event.result as GenerationResult;cached(r.pngPath).then(url=>{$<HTMLImageElement>('single-preview').src=url;$('single-preview').hidden=false;$('preview-empty').hidden=true;}).catch(showError);}if(activeKind==='finals'){$('final-output').replaceChildren();for(const r of event.result as GenerationResult[]){const button=document.createElement('button');button.textContent=r.settings.labels?'Open labeled final':'Open unlabeled final';button.onclick=()=>{api.openPath(r.pngPath).catch(showError);};$('final-output').append(button);}}}
  if(event.type==='cancelled'){setBusy(false);status('Cancelled. Completed outputs are preserved.');}
  if(event.type==='error'){setBusy(false);status('Generation failed.');showError(event.error?.message??'Unknown error');}
});
refreshGallery();
